apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: '0.28.1'
    helm:
      values: |
        server:
          enabled: true
          ingress:
            enabled: true
            annotations: 
              |
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.middlewares: prod-redirect-https@kubernetescrd
            ingressClassName: traefik
            activeService: true
            hosts:
              - host: vault.csnguyen.de
            tls: []
              - secretName: hashicorp-vault-tls
              hosts:
                - vault.csnguyen.de
  destination:
    namespace: hashicorp-vault
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
