apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: rancher
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    chart: rancher
    targetRevision: '2.8.5'
    helm:
      values: |
        replicas: 1
        hostname: rancher.csnguyen.de
        ingress:
          enabled: true
          includeDefaultExtraAnnotations: false
          extraAnnotations: 
          	cert-manager.io/cluster-issuer: letsencrypt-prod
          	traefik.ingress.kubernetes.io/router.middlewares: prod-redirect-https@kubernetescrd
          ingressClassName: traefik
          tls:
            source: secret
            secretName: tls-rancher-ingress
  destination:
    namespace: rancher
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
