apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-portfolio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: default
  source:
    path: helm-charts/web-portfolio
    repoURL: https://github.com/Sony2k20/argo-applications.git
    targetRevision: HEAD
  syncPolicy: {}
    # automated:
    #   prune: true
    # syncOptions:
    #   - CreateNamespace=true