replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

github:
  repo: "https://github.com/Sony2k20/web-portfolio"
  branch: "master"

service:
  type: ClusterIP
  port: 80

ingress:
  host: csnguyen.de
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      prod-redirect-https@kubernetescrd

livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80